// This file is generated by scripts/sync-youtube-views.mjs
// Do not edit manually. Run `npm run sync:views` to refresh.

export const YOUTUBE_VIEWS: Record<string, number> = {
  "QORbytC_h94": 412345,
  "Ww1RrOeTq78": 278901,
  "6cp7l0FEYlY": 543210,
  "JqwL7ism1CU": 125000,
  "ykbchtupA14": 332100,
  "aEWYjV86UdU": 1230000,
  "oIJ5-wiUE4g": 980000,
  "y_OYSYeSwL0": 1560000,
  "WJr9fLQlrcw": 720000,
  "JgMRlTDxfUQ": 2100000
}
